Projeto=Be_Talent_TestTec_Web-API
Camada=API
Ferramenta=Newman + Allure
Base.URL=https://restful-booker.herokuapp.com
Node.Version=20
Newman.Version=6.2.x
Allure.Reporter=newman-reporter-allure@3.8.0
SO=Ubuntu (GitHub Actions runner)
